version: "3.6"

services:
  sql-to-rce:
    build: ./web
    restart: 'always'
    ports:
      - "8000:80"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./web/index:/var/www/html



