FROM ubuntu/mysql:latest

# Install packages
RUN apt update -y && apt install apache2 php libapache2-mod-php php-mysql -y
    
# Setup database user
RUN usermod -a -G mysql www-data
    
# Init database
COPY ./database /docker-entrypoint-initdb.d
    
# Copy challenge files to default document root
COPY ./index /var/www/html
    
# Remove unsused index.html
WORKDIR /var/www/html/
RUN rm index.html
    
# Set up permissions for owner
RUN chown -R root:www-data /var/www/html
RUN chmod 750 /var/www/html
RUN find . -type f -exec chmod 640 {} \;
RUN find . -type d -exec chmod 750 {} \;
    
# Add write permission for upload file
RUN chmod +t -R /var/www/html/
    
# Start services: apache2 and mysql
CMD ["bash", "-c", "/usr/sbin/apache2ctl start && /usr/local/bin/docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password --secure-file-priv=/var/www/html"]